<?php
$urlPattern = $_SERVER['REQUEST_URI'];

$formatUrl = function($page) use ($urlPattern) {
    if (!preg_match('/page/', $urlPattern))
        return $urlPattern . '/page/' . (int) $page;
    else
        return preg_replace('@/page/\d@', '/page/' . (int) $page, $urlPattern);
};


if ($this->pageCount):
    ?>

    <div >

        <center><ul class="pagination pagination-sm">
                <?php if (isset($this->previous)): ?>
                    <li>
                        <a href="<?php echo $formatUrl($this->previous); ?>">&laquo;</a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">&laquo;</a>
                    </li>
                <?php endif; ?>

                <?php foreach ($this->pagesInRange as $page): ?>

                    <?php if ($page != $this->current): ?>
                        <li>
                            <a href="<?php echo $formatUrl($page); ?>"><?php echo $page ?></a>
                        </li>

                    <?php else: ?>
                        <li class="active">
                            <a href="#"><?php echo $page ?></a>
                        </li>
                    <?php endif; ?>

                <?php endforeach; ?>

                <?php if (isset($this->next)): ?>

                    <li>
                        <a href="<?php echo $formatUrl($this->next); ?>">&raquo;</a>
                    </li>
                <?php else: ?>
                    <li class="disabled">
                        <a href="#">&raquo;</a>
                    </li>
                <?php endif; ?>


            </ul></center>
    </div>
<?php endif; ?>